export const env = {
  NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL ?? '',
  NEXT_PUBLIC_API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL ?? '',
  NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS_ID ?? '',
  DATABASE_URL: process.env.DATABASE_URL ?? '',
  DATABASE_USER: process.env.DATABASE_USER ?? '',
  DATABASE_PASSWORD: process.env.DATABASE_PASSWORD ?? '',
  EMAIL_SERVER_HOST: process.env.EMAIL_SERVER_HOST ?? '',
  EMAIL_SERVER_PORT: process.env.EMAIL_SERVER_PORT ?? '',
  EMAIL_SERVER_USER: process.env.EMAIL_SERVER_USER ?? '',
  EMAIL_SERVER_PASSWORD: process.env.EMAIL_SERVER_PASSWORD ?? '',
  STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY ?? '',
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY ?? ''
};
